photoalbum_app/models.py
from sqlalchemy_utils import URLType

from flask_login import UserMixin

from photoalbum_app import db
# Create your models here.
class User(UserMixin, db.Model):
    """User Model"""
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)


class Album(db.Model):
    """Album Model"""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(20), nullable=False)
    description = db.Column(db.String(200), nullable=False)

    """ Relationship """
    photos = db.relationship('Photo', back_populates='album')

    """ Relationship """
    created_by = db.relationship('User')

    """Foreign Key"""
    created_by_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Photo(db.Model):
    """Photo Model"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    small_description = db.Column(db.String(200), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    photo_url = db.Column(URLType)

    ##########################################
    #     User Relationship/Foreign Key      #
    ##########################################

    """ Relationship """
    created_by = db.relationship('User')

    """Foreign Key"""
    created_by_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    ##########################################
    #    Album Relationship/Foreign Key      #
    ##########################################
    """Foreign Key"""
    album_id = db.Column(db.Integer, db.ForeignKey('album.id'), nullable=False)

    """Relationship"""
    album = db.relationship('Album', back_populates='photos')
    

photoalbum_app/main/forms.py
from photoalbum_app.models import Album
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, URL

# Create your forms here.

class AlbumForm(FlaskForm):
    """Album Form for created new Albums"""
    title = StringField("Title", validators=[DataRequired(), Length(min=5, max=20)])
    description = StringField("Description", validators=[DataRequired(), Length(min=5, max=200)])
    submit = SubmitField("Submit")

class PhotoForm(FlaskForm):
    """Album Form for created new Albums"""
    name = StringField("Name", validators=[DataRequired(), Length(max=20)])
    photo_url = StringField("Photo URL", validators=[URL(require_tld=True)])
    location = StringField("Location", validators=[DataRequired(), Length(min=5, max=100)])
    date = DateField("Date", format= '%Y-%m-%d')
    small_description = StringField("Small Description", validators=[DataRequired(), Length(min=5, max=100)])
    album = QuerySelectField('Album', query_factory=lambda: Album.query, allow_blank=False)
    submit = SubmitField("Submit")

photoalbum_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

from photoalbum_app.config import Config
import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)

db = SQLAlchemy(app)

###########################
# Authentication
###########################

# TODO: Add authentication setup code here!
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

from photoalbum_app.models import User

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)
###########################
# Blueprints
###########################
bcrypt = Bcrypt(app)

from photoalbum_app.main.routes import main as main_routes
app.register_blueprint(main_routes)

from photoalbum_app.auth.routes import auth as auth_routes
app.register_blueprint(auth_routes)

with app.app_context():
    db.create_all()

photoalbum_app/main/routes.py
from os import name
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required

from photoalbum_app import app, db

from photoalbum_app.main.forms import AlbumForm, PhotoForm
from photoalbum_app.models import Album, Photo

main = Blueprint('main', __name__)

# Create your routes here.
@main.route('/')
def homepage():
    all_albums = Album.query.all()
    return render_template('home.html', all_albums=all_albums)

@main.route('/create_album', methods=['GET', 'POST'])
@login_required
def create_album():
    form = AlbumForm()

    if form.validate_on_submit():
        new_album = Album(
            title=form.title.data,
            description=form.description.data
        )
        db.session.add(new_album)
        
        db.session.commit()
        flash('Your new album has been added!')

        return redirect(url_for('main.homepage', album_id=new_album.id))
    return render_template('create_album.html', form=form)

@main.route('/album/<album_id>', methods=['GET', 'POST'])
@login_required
def album_info(album_id):
    album = Album.query.get(album_id)

    form = AlbumForm(obj=album)

    if form.validate_on_submit():
        album.title = form.title.data
        album.description = form.description.data

        db.session.commit()
        flash('Your Album has been updated!')

        return redirect(url_for('main.homepage', album_id=album.id))        
    return render_template('album_info.html', album=album, form=form)

@main.route('/create_photo', methods=['GET', 'POST'])
@login_required
def create_photo():
    form = PhotoForm()
    if form.validate_on_submit():
        new_photo = Photo(
            name=form.name.data,
            photo_url=form.photo_url.data,
            location=form.location.data,
            date=form.date.data,
            album=form.album.data,
            small_description=form.small_description.data
        )
        db.session.add(new_photo)
        db.session.commit()

        flash('Photo has been added to the designated album')
        
        return redirect(url_for('main.homepage', photo_id=new_photo.id))
    return render_template('create_photo.html', form=form)

@main.route('/photo/<photo_id>', methods=['POST', 'GET'])
@login_required
def photo_info(photo_id):
    photo = Photo.query.get(photo_id)

    form = PhotoForm(obj=photo)

    if form.validate_on_submit():
        photo.name = form.name.data
        photo.photo_url = form.photo_url.data
        photo.location = form.location.data
        photo.date = form.date.data
        photo.album = form.album.data
        photo.small_description = form.small_description.data

        db.session.commit()
        flash('Your photo has been successfully updated')

        return redirect(url_for('main.photo_info', photo_id=photo.id))        
    return render_template('photo_info.html', photo=photo, form=form)

photoalbum_app/templates/album_info.html
{% extends 'base.html' %}
{% block content %}

<h1>{{album.title}}</h1>

<h2>Desciption: {{album.description}}</h2>

<h2>Photos:</h2>

{% for photo in album.photos %}
<div class="photos">
    <div class="photo_details">

        <a href="/photo/{{photo.id}}">
            <p>{{ photo.name }}</p>
            <img src="{{ photo.photo_url }}" alt="{{ photo.name }}" width="100">
        </a>
        <p>Description: {{ photo.small_description }}</p>
        <p>Location: {{ photo.location }}</p>
    </div>
</div>
{% endfor %}

<h1>Edit Your Album</h1>

<form method='POST' action="{{url_for('main.album_info', album_id=album.id)}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>Make Your Changes Below</legend>
        {{form.title.label}}
        {{form.title}}

        {{form.description.label}}
        {{form.description}}

        {{form.submit}}
    </fieldset>
</form>

{% endblock %}

photoalbum_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Photo Album</title>
        <link rel="stylesheet" href="/static/style.css">
        
    </head>
    <body>
        <!-- Add base html here. -->
        <div id="main">
            <nav>
                
                <div>
                    
                    {% for message in get_flashed_messages() %}
                        <legend>{{message}}</legend>
                    {% endfor %}
                    <a href="/">Home Page</a>
                    {% if current_user.is_authenticated %}
                    <a href="/logout">Log Out</a>
                    <a href="/create_album">Create Album</a>
                    <a href="/create_photo">Add a Photo</a>

                    {% else %}

                    <a href="/signup">Sign Up</a>
                    <a href="/login">Login</a>

                    {% endif %}
                </div>
            </nav>

        </div>
        {% block content %}{% endblock %}
    </body>
</html>

photoalbum_app/templates/create_album.html
{% extends 'base.html' %}
{% block content %}

<h1>Album</h1>

<form action="{{url_for('main.create_album')}}" method="POST">
    {{form.csrf_token}}
    <fieldset>
        <legend>
            Enter Your Album information below
        </legend>
        {{form.title.label}}
        {{form.title}}

        {{form.description.label}}
        {{form.description}}

        {{form.submit}}
    </fieldset>
</form>
{% endblock %}

photoalbum_app/templates/create_photo.html
{% extends 'base.html' %}
{% block content %}

<h1>Add Photo</h1>

<form action="{{url_for('main.create_photo')}}" method="POST">
    {{form.csrf_token}}
    <fieldset>
        <legend>
            Photo info below:
        </legend>
        {{form.name.label}}
        {{form.name}}

        {{form.photo_url.label}}
        {{form.photo_url}}

        {{form.album.label}}
        {{form.album}}

        {{form.date.label}}
        {{form.date}}

        {{form.small_description.label}}
        {{form.small_description}}

        {{form.location.label}}
        {{form.location}}

        {{form.submit}}
    </fieldset>
</form>

{% endblock %}

photoalbum_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Photo Album Website</h1>

<h2>Your Albums:</h2>

{% for album in all_albums%}

<div class="album">
    <a href="/album/{{ album.id }}">{{ album.title }}</a>
    {{ album.photos|length }} photos in album

</div>
{% endfor %}
{% endblock %}

photoalbum_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

photoalbum_app/templates/photo_info.html
{% extends 'base.html' %} {% block content %}
<h1>Photo:{{ photo.name }}</h1>
<p><img src="{{ photo.photo_url }}" width="200"></p>
<p>Desciption: {{ photo.small_description }}</p>
<p>Taken: {{ photo.date}}</p>
<p>Located: {{photo.location}}</p>

<p>Edit Photo</p>

<form method='POST' action="{{url_for('main.photo_info', photo_id=photo.id)}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>
            Update information below:
        </legend>
        {{form.name.label}}
        {{form.name}}

        {{form.photo_url.label}}
        {{form.photo_url}}

        {{form.album.label}}
        {{form.album}}

        {{form.date.label}}
        {{form.date}}

        {{form.small_description.label}}
        {{form.small_description}}

        {{form.location.label}}
        {{form.location}}

        {{form.submit}}
    </fieldset>
</form>

{% endblock %}

photoalbum_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}